Add install script, rename shared-functions, redo the way they are loaded

diff --git a/jwb-index b/jwb-index
--- a/jwb-index
+++ b/jwb-index
@@ -4,14 +4,25 @@
 # Index JW Broadcasting (tv.jw.org)
 #
 
-if [[ $1 = -x ]]; then
-    export debug=1
-    shift
-fi
+load_shared_code()
+{
+    for code in "$SHARED" ./shared-functions /usr/local/lib/jw-scripts/shared-functions; do
+	if [[ -f $code ]]; then
+	    if source "$code"; then
+		break
+	    else
+		echo "Failed to load shared functions" 1&>2
+		exit 1
+	    fi
+	fi
+    done
 
-if ((debug)); then
-    set -x
-fi
+    if [[ $? != 0 ]]; then
+	echo "Cannot find shared functions file" 1>&2
+	echo "You can set the default path with the variable SHARED" 1>&2
+	exit 1
+    fi
+}
 
 show_help()
 {
@@ -161,19 +172,7 @@ lang_list()
     exit
 }
 
-# Load shared code
-[[ $SHARED ]] || SHARED="shared-functions.sh"
-if [[ -f $SHARED ]]; then
-    source $SHARED
-else
-    cat<<EOF 1>&2
-Cannot find the shared code at $SHARED
-You can set the default path with the variable SHARED
-EOF
-    exit 1
-fi
-
-! ((child)) && requirement_check
+load_shared_code
 
 read_arguments --help:show_help\
                --list-langs:lang=none \
@@ -209,6 +208,8 @@ mainurl="http://mediator.jw.org/v1/categories/$lang/${maincode}?detailed=1"
 # Things that only the parent may do
 # or that's only needed once
 if ! ((child)); then
+    # Do we have all we need?
+    requirement_check
     # Check that lang is valid
     check_lang "$lang" "$langurl" "\"code\":\"$lang\"" || lang_list
     # Add a subdir
diff --git a/nwt-index b/nwt-index
--- a/nwt-index
+++ b/nwt-index
@@ -5,6 +5,26 @@
 # the New World Translation of the Holy Scriptures
 #
 
+load_shared_code()
+{
+    for code in "$SHARED" ./shared-functions /usr/local/lib/jw-scripts/shared-functions; do
+	if [[ -f $code ]]; then
+	    if source "$code"; then
+		break
+	    else
+		echo "Failed to load shared functions" 1&>2
+		exit 1
+	    fi
+	fi
+    done
+
+    if [[ $? != 0 ]]; then
+	echo "Cannot find shared functions file" 1>&2
+	echo "You can set the default path with the variable SHARED" 1>&2
+	exit 1
+    fi
+}
+
 show_help()
 {
     cat<<EOF
@@ -105,19 +125,7 @@ lang_list()
     exit
 }
 
-# Load shared code
-[[ $SHARED ]] || SHARED="shared-functions.sh"
-if [[ -f $SHARED ]]; then
-    source $SHARED
-else
-    cat<<EOF 1>&2
-Cannot find the shared code at $SHARED
-You can set the default path with the variable SHARED
-EOF
-    exit 1
-fi
-
-! ((child)) && requirement_check
+load_shared_code
 
 read_arguments --help:show_help \
                --lang=lang \
@@ -148,6 +156,8 @@ mainurl="http://www.jw.org/apps/TRGCHlZRQVNYVrXF?booknum=$maincode&output=json&p
 # Things that only the parent may do
 # or that's only needed once
 if ! ((child)); then
+    # Do we have all we need?
+    requirement_check
     # Check that lang is valid
     check_lang "$lang" "$langurl" "\"$lang\":{\"name\":" || lang_list
     # Only the parent process has a subdir
diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -1,7 +1,13 @@
-#!/bin/bash
+# -*- shell-script -*-
 #
 # functions for jw-scripts
 #
+# Variables that changes the behaviour:
+# filesystem   If true save to dir, else write playlist
+# download     If true download the media files
+# child        If true we are subprocess (affects some things)
+# hascurl      If true use curl, else use wget
+# 
 
 error()
 {
@@ -52,7 +58,7 @@ unsquash_file()
     if [[ $@ ]]; then
         # Append \| to all parameters
         # and remove the last one
-        keywordstring="$(printf '%s\|' "$@" | sed 's/\\|$//')"
+        keywordstring="$(printf '%s\|' "$@" | sed 's/\\|$//')" || error "Error in unsquash_file()"
     else
         # Match everything that's not a citation mark
         keywordstring='[^"]*'
