Make smart update with the --latest flag work as intended

diff --git a/jwb-index b/jwb-index
--- a/jwb-index
+++ b/jwb-index
@@ -37,7 +37,6 @@ Usage: jwb-index [options] [DIRECTORY]
   --latest              Index "Latest Videos" instead of "Video on Demand"
   --download            Make videos available offline
   --filesystem          Organize videos in directories
-  --plex		Plex compatibility (--download, --filesystem)
   --clean               Clean out all old files exept downloaded videos
   DIRECTORY             Directory to save the playlists or videos in
 Advanced options:
@@ -61,8 +60,8 @@ EOF
 #
 parse_lines()
 {
-    # Create empty dir and playlist
-    initialize_dir "$datadir" "$maincode"
+    # Create empty playlist for this category
+    ! ((filesystem)) && reset_playlist "$datadir/$maincode.m3u"
 
     # Read stdin
     while read -r input; do
@@ -108,9 +107,15 @@ parse_lines()
             title:*)
                 # If there is a title an URL, save them
                 if [[ $title && $url ]]; then
-                    write_media "$title" "$url" "$datadir" "$maincode"
-                    # Unset title and URL so they don't get repeated
-                    unset title url
+		    if ((latest)) && [[ $realcode ]]; then
+			# If this belongs to other category, add it to that one
+			write_media "$title" "$url" "$datadir" "$realcode"
+			unset realcode
+		    else
+			write_media "$title" "$url" "$datadir" "$maincode"
+		    fi
+		    # Unset title and URL so they don't get repeated
+		    unset title url realcode
                 fi
 
                 title="${input#*:}"
@@ -181,7 +186,7 @@ read_arguments --help:show_help\
                --quality=quality \
                --child:child=1\
                --no-subs:nosubtitles=1 \
-               --latest:maincode=LatestVideos \
+               --latest:maincode=LatestVideos\;latest=1 \
                --download:download=1 \
                --no-recursive:norecursive=1 \
                --json:json=1 \
@@ -191,7 +196,7 @@ read_arguments --help:show_help\
                -- \
                "$@" || exit 1
 
-export lang maincode nosubtitles quality download norecursive maxrate filesystem child
+export lang maincode nosubtitles quality download norecursive maxrate filesystem latest
 [[ ${#arguments[@]} -gt 1 ]] && error "Too many arguments" # $arguments gets set by read_arguments()
 
 # Assign variables
@@ -212,14 +217,16 @@ if ! ((child)); then
     requirement_check
     # Check that lang is valid
     check_lang "$lang" "$langurl" "\"code\":\"$lang\"" || lang_list
-    # Check datadir and make absolute
-    if [[ -d $datadir ]]; then
-	datadir="$(realpath "$datadir")"
-    else
-	error "$datadir: Destination directory does not exist"
-    fi
+    # Check datadir
+    [[ -d $datadir ]] || error "$datadir: Destination directory does not exist"
+    # Make path absolute
+    datadir="$(realpath "$datadir")"
     # Add a subdir
     datadir="$datadir/jwb-$lang"
+    # Create subdir
+    if [[ ! -d $datadir ]]; then
+        mkdir -p "$datadir" || error "$datadir: Failed to create directory"
+    fi
     # Cleaning
     ((clean)) && clean_dir "$datadir"
     # Remove the history file when we exit
@@ -238,7 +245,7 @@ fi
 
 # Download and parse the JSON file
 download_file "$mainurl" \
-    | unsquash_file key name title progressiveDownloadURL parentCategory \
+    | unsquash_file key name title progressiveDownloadURL parentCategory primaryCategory \
     | parse_lines
 
 
diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -37,7 +37,14 @@ clean_dir()
 create_link()
 {
     [[ $1 && $2 ]] || error "Error in create_link()"
+    local destdir
+    destdir="$(dirname "$2")" || error "Error in create_link()"
 
+    # Create dir if not there
+    if [[ ! -d $destdir ]]; then
+	mkdir -p "$destdir" || error "$destdir: Failed to create directory"
+    fi
+        
     # Does link exist?
     if [[ -L "$2" ]]; then
 	# Is link destination same as we want?
@@ -97,27 +104,6 @@ unsquash_file()
             p
         }
 ' || error "Failed to format JSON"
-}
-
-# Create empty dir and playlist
-# Args: DATADIR CODE
-initialize_dir()
-{
-    local datadir="$1"
-    local code="$2"
-
-    [[ $datadir && $code ]] || error "Error in initialize_dir()"
-
-    ((filesystem)) && datadir="$datadir/$code"
-    
-    # Create directory
-    if [[ ! -d $datadir ]]; then
-        mkdir -p "$datadir" || error "$datadir: Failed to create directory"
-    fi
-
-    ! ((filesystem)) && reset_playlist "$datadir/$code.m3u"
-    
-    return 0
 }
 
 # Create a link to the CODE outside DATADIR for easy access
@@ -206,7 +192,7 @@ write_media()
 
 reset_playlist()
 {
-    printf '%s\n' "#EXTM3U" > "$1"
+    printf '%s\n' "#EXTM3U" > "$1" || error "$1: Failed to write to playlist"
 }
 
 # Args: [-r] NAME LINK FILE
@@ -215,10 +201,12 @@ write_to_playlist()
     local title="$1"
     local link="$2"
     local file="$3"
+    local dir
     [[ $title && $link && $file ]] || error "Error in write_to_playlist()"
-
-    # Reset the file
-    if [[ ! -e $file ]]; then
+    dir="$(dirname "$file")" || error "Error in write_to_playlist()"
+        
+    # Reset the file if empty
+    if [[ ! -f $file ]]; then
 	reset_playlist "$file"
     fi
 
@@ -230,6 +218,9 @@ write_to_playlist()
 	[[ $subdir ]] || error "Error in write_to_playlist()"
 	link="$subdir/$link"
     fi
+
+    # If link already is written to file, skip it
+    grep -q "^$link$" "$file" && return 0
     
     printf '%s\n' "#EXTINF:0,$title" "$link" >> "$file" || error "$file: Failed to write to playlist"
 }
@@ -240,8 +231,6 @@ download_file()
 {
     [[ $1 ]] || error "Error in download_file()"
 
-    echo "$1" 1>&2
-    
     if ((hascurl)); then
         curl ${maxrate:+--limit-rate "$maxrate"} --silent "$1" || error "Failed to download file"
     else
