Changes in variable names, config file

diff --git a/jwb-index b/jwb-index
--- a/jwb-index
+++ b/jwb-index
@@ -27,44 +27,43 @@ load_shared_code
 show_help()
 {
     cat<<EOF
-Usage: jwb-index --mode MODE [OPTIONS] [DIRECTORY]
+Usage: jwb-index [OPTIONS] [DIRECTORY]
 Index videos at tv.jw.org
 
+Options:
+  --category CODENAMES  Comma-separated list of categories to index
+  --checksum            Verify integrity of video files (default)
+  --clean               Clean out all files except downloaded videos
+  --config FILE         Custom configuration file
+  --download            Download videos
+  --json                Only show the formatted JSON file (debug)
+  --lang CODE           Set language
+  --latest              Index "Latest Videos" instead of "Video on Demand"
+  --limit-rate RATE     Download rate for videos, 0 disables limit
+  --list-langs          Show a list of available language codes
+  --mode MODE           Set output mode, see "Modes".
+  --no-recursive        Don't parse sub-categories
+  --no-subsubtitles     Prefer unsubtitled videos
+  --no-timestamp        Don't change timestamps on files
+  --quality NUM         Maximum quality: 240, 360, 480 or 720
+  --quiet               Don't show progress
+  --since DATE          Only save videos newer than DATE
+  --subtitles           Prefer subtitled videos (default)
+  --timestamp           Change timestamps on files (default)
+  DIRECTORY             Directory to save the playlists or videos in
+
 Modes:
-  filesystem            Create symlinks and directories. Compatible with Plex.
-			  This mode is only really useful with --download.
+  filesystem            Create a directory tree with symlinks. Compatible with Plex.
   html			Generate a set of HTML pages with links to the videos.
   m3u                   Create a "browsable" m3u playlist. Compatible with Kodi.
   m3ucompat             Create multiple m3u playlists. Should work with most players.
-  urllist               Output a list of URLs or files to stdout. 
-
-Options:
-  --clean               Clean out all old files except downloaded videos
-  --download            Download videos
-  --lang CODE           Set language
-  --latest              Index "Latest Videos" instead of "Video on Demand"
-  --list-langs          Show a list of available language codes
-  --no-subs             Prefer unsubtitled videos
-  --quality NUM         Select maximum quality: 240, 360, 480 or 720
-  --quiet               Don't show status
-  --since DATE          Only save videos newer than DATE
-  DIRECTORY             Directory to save the playlists or videos in
-
-Advanced options:
-  --category CODENAMES  Comma separated list of categories to index. Default:
-                          VideoOnDemand
-  --json                Don't parse the JSON file, just show it (debug)
-  --limit-rate RATE     Maximum download rate for videos, default is
-                          500k (500 kilobytes per second), 0 disables limit
-  --no-checksum         Don't verify integrity of video files 
-  --no-recursive        Don't automatically download sub-categories
-  --no-timestamp        Don't change timestamps on files
+  urllist               Output a list of URLs or files to stdout (default). 
 
 EOF
     exit
 }
 
-# Save a media link
+# Save a video
 save()
 {
     # If there is a title and URL, save them
@@ -88,10 +87,10 @@ save()
 	 
 	[[ ${url[$i]} ]] || err || return 1
 	
-	# If this belongs to other category (realcode), add it to that one
-	write_media "$title" "${url[$i]}" "$datadir" "${realcode:-$maincode}" "$mainname" "${checksum[$i]}" "${filesize[$i]}" "$time" || return 1
+	# If this belongs to other category (real_category), add it to that one
+	write_media "$title" "${url[$i]}" "$dir" "${real_category:-$main_category}" "$main_category_name" "${checksum[$i]}" "${filesize[$i]}" "$time" || return 1
 	# Unset variables so they don't get repeated                                                                           
-        unset title url realcode checksum filesize time qualitylabel subtitled urlindex
+        unset title url real_category checksum filesize time qualitylabel subtitled urlindex
     fi
 }
 
@@ -136,9 +135,10 @@ parse_lines()
                 ;;
 
             primaryCategory:*)
-		# Don't use "realcode" in m3ucompat mode since there is no equivalent
-		# "realname" that can be used as filename
-                ((latest)) && [[ $mode != m3ucompat ]] && realcode="${input#*:}"
+		# The LatestVideos actually belong in another category. Use that one.
+		# Execept in m3ucompat mode since there is no spoken name for the category
+		# that can be used in the filename
+                [[ $main_category = LatestVideos && $mode != m3ucompat ]] && real_category="${input#*:}"
                 ;;
 
             name:*)
@@ -149,21 +149,21 @@ parse_lines()
 		name="${input#*:}"
 
                 # First category (self)
-                if [[ $code = "$maincode" ]]; then
-		    mainname="$name"
+                if [[ $code = "$main_category" ]]; then
+		    main_category_name="$name"
 		    # Empty out the playlist for this category
-		    write_empty "$datadir" "$code" "$name" || err
+		    write_empty "$dir" "$code" "$name" || err
                     continue
                 fi
 
-                write_subdir "${name^^*}" "$code" "$datadir" "$maincode" "$mainname" || err || continue
+                write_subdir "${name^^*}" "$code" "$dir" "$main_category" "$main_category_name" || err || continue
 
                 # Start a new instance - download and parse category
                 if ! ((norecursive)); then
                     # Don't download categories we've already checked
-                    grep -q "^$code$" "$histfile" && continue
+                    grep -q "^$code$" "$history" && continue
 
-                    ("$0" --child --category "$code" "$datadir")
+                    ("$0" --child --category "$code" "$dir")
 
 		    case $? in
 			1) err "child process failed" ;;
@@ -186,7 +186,7 @@ parse_lines()
                 ;;
 
 	    checksum:*)
-		((nomd5)) && continue
+		((checksums)) || continue
 		[[ -v checksum[$urlindex] ]] || checksum[$urlindex]="${input#*:}"
 		;;
 
@@ -205,7 +205,7 @@ parse_lines()
 		;;
 
 	    firstPublished:*)
-		((notime)) || time="${input#*:}"
+		((timestamps)) && time="${input#*:}"
 		;;
 
         esac
@@ -218,99 +218,125 @@ parse_lines()
     return 0
 }
 
+
 trap 'echo "aborted (PID $$)" 1>&2; exit 2' SIGTERM SIGINT SIGHUP
 
+
+
+### LOAD SETTINGS AND PARSE ARGUMENTS
+
+unset clean child json norecursive quiet
+export checksums download mode subtitles timestamps quiet
+
 read_arguments --help:show_help \
-               --list-langs:lang=none \
-               --lang=lang \
-               --category=maincode \
-               --quality=quality \
+               --category=categories \
+	       --checksum:checksums=1 \
                --child:child=1 \
-               --no-subs:subtitles=0 \
-               --latest:maincode=LatestVideos\;latest=1 \
-               --download:download=1 \
-               --no-recursive:norecursive=1 \
-               --json:json=1 \
-               --filesystem:mode=filesystem \
-	       --mode=mode \
-	       --limit-rate=maxrate \
 	       --clean:clean=1 \
+	       --config=conf \
+	       --download:download=1 \
+	       --filesystem:mode=filesystem \
+               --json:json=1 \
+               --lang=lang \
+               --latest:categories=LatestVideos \
+	       --limit-rate=maxrate \
+	       --list-langs:lang=none \
+	       --mode=mode \
+	       --no-checksum:checksums=0 \
+               --no-recursive:norecursive=1 \
+               --no-subtitles:subtitles=0 \
+	       --no-timestamp:timestamps=0 \
+               --quality=quality \
 	       --quiet:quiet=1 \
-	       --no-checksum:nomd5=1 \
-	       --no-timestamp:notime=1 \
 	       --since=since \
-               -- \
-               "$@"
+	       --subtitles:subtitles=1 \
+	       --timestamp:timestamps=1 \
+	       -- "$@" || exit 1
 
-export lang maincode subtitles quality download norecursive maxrate mode latest histfile quiet nomd5 notime since
 [[ ${#arguments[@]} -gt 1 ]] && msg "too many arguments" && exit 1 # $arguments gets set by read_arguments()
+dir="${arguments[0]}"
 
-# Assign variables
-[[ $maxrate ]] || maxrate=500k
-[[ $maincode ]] || maincode=VideoOnDemand
-[[ $quality ]] || quality=720
-[[ $lang ]] || lang=E
-[[ $subtitles ]] || subtitles=1
-datadir="${arguments[0]:-.}"
 
-# Debug JSON
-if ((json)); then
-    mainurl="https://mediator.jw.org/v1/categories/$lang/${maincode%%,*}?detailed=1"
-    download_file "$mainurl" | unsquash_file | less
-    exit
-fi
 
-[[ $mode ]] || msg "no mode specified" || exit 1
-[[ $mode =~ ^(m3u|m3ucompat|filesystem|urllist|html)$ ]] || msg "$mode: unknown mode" || exit 1
+### CHECKS AND PREPARATIONS
 
-# Things that only the parent may do
-# or that's only needed once
 if ! ((child)); then
-    # Do we have all we need?
+
     requirement_check sed curl realpath mktemp
+
+    load_settings jwb-index "$conf" \
+		  categories=VideoOnDemand \
+		  checksums=1 \
+		  dir=. \
+		  download=0 \
+		  jwb_script=jwb-index \
+		  lang=E \
+		  limit_rate=500k \
+		  mode=urllist \
+		  quality=720 \
+		  since= \
+		  subtitles=1 \
+		  timestamps=1 \
+	|| exit 1
+
     # Check that lang is valid
+    # Note: this must be done before anything else happens
+    # so we can display a language list if needed
     jwb_check_lang "$lang" || exit 1
-    # Check datadir
-    [[ -d $datadir ]] || msg "$datadir: destination directory does not exist" || exit 1
-    # Make path absolute
-    datadir="$(realpath "$datadir")"
-    # Add a subdir
-    datadir="$datadir/jwb-$lang"
-    # Cleaning
-    ((clean)) && clean_dir "$datadir"
-    # History only needed when "recursing"
-    if ((norecursive)); then
-	histfile=/dev/null
-    else
-	# Create history file
-	histfile="$(mktemp /tmp/jwb-index-XXXXXX.tmp)" || crash "failed to create temp file"
-	# Remove the history file when we exit
-	trap '[[ -e $histfile ]] && rm "$histfile"' EXIT
-    fi
-    # Convert date to seconds
+    
+    # Valid modes
+    [[ $mode =~ ^(m3u|m3ucompat|filesystem|urllist|html)$ ]] || msg "$mode: unknown mode" || exit 1
+
+    # Convert date argument to seconds
     if [[ $since ]]; then
 	since="$(date -d "$since" +%s)" || exit 1
     fi
+    
+    # Debug JSON
+    # (do this before any other things get done)
+    if ((json)); then
+	main_url="https://mediator.jw.org/v1/categories/$lang/${category%%,*}?detailed=1"
+	download_file "$main_url" | unsquash_file | less
+	exit
+    fi
+
+    # Check dir
+    [[ -d $dir ]] || msg "$dir: directory does not exist" || exit 1
+    # Make path absolute
+    dir="$(realpath "$dir")"
+    # Add a subdir
+    dir="$dir/jwb-$lang"
+    # Cleaning
+    ((clean)) && clean_dir "$dir"
+    # History only needed when "recursing"
+    if ((norecursive)); then
+	export history=/dev/null
+    else
+	# Create history file
+	export history
+	history="$(mktemp /tmp/jwb-index-XXXXXX.tmp)" || crash "failed to create temp file"
+	# Remove the history file when we exit
+	trap '[[ -f $history ]] && rm "$history"' EXIT
+    fi
 fi
 
-# Split codes where commas are
-OLDIFS="$IFS"
-IFS=,
-maincodes=($maincode)
-IFS="$OLDIFS"
 
-for maincode in "${maincodes[@]}"; do
+
+### MAIN LOOP
+
+# Split categories list where commas are
+for main_category in "${categories[@]//,/ }"; do
     
-    mainurl="https://mediator.jw.org/v1/categories/$lang/${maincode}?detailed=1"
+    main_url="https://mediator.jw.org/v1/categories/$lang/${main_category}?detailed=1"
     
     # Write to the history file
     # and show a message with our progress
-    [[ $histfile ]] || crash "histfile: variable empty, this should not happen"
-    echo "$maincode" >> "$histfile" || crash "$histfile: failed to write to temp file"
-    ((quiet)) || echo "$maincode" 1>&2
+    [[ $history ]] || crash "history: variable empty, this should not happen"
+    echo "$main_category" >> "$history" || crash "$history: failed to write to temp file"
+    ((quiet)) || echo "$main_category" 1>&2
 
     # Download and parse the JSON file
-    download_file "$mainurl" \
+    download_file "$main_url" \
     	| unsquash_file status key name title progressiveDownloadURL parentCategory checksum filesize firstPublished subtitled label \
 	| parse_lines
 
