Keep up with changes to shared code

diff --git a/nwt-index b/nwt-index
--- a/nwt-index
+++ b/nwt-index
@@ -60,8 +60,8 @@ EOF
 #
 parse_lines()
 {
-    # Create empty dir and playlist
-    initialize_dir "$datadir" "$maincode"
+    # Create empty playlist for this category
+    ! ((filesystem)) && reset_playlist "$datadir/$maincode.m3u"
 
     # Read stdin
     # Use -r because we want to keep the backslashes a bit longer
@@ -141,7 +141,7 @@ read_arguments --help:show_help \
                -- \
                "$@" || exit 1
 
-export lang maincode bible maxrate download filesystem child
+export lang maincode bible maxrate download filesystem
 [[ ${#arguments[@]} -gt 1 ]] && error "Too many arguments" # $arguments gets set by read_arguments()
 
 # Assign variables
@@ -160,14 +160,16 @@ if ! ((child)); then
     requirement_check
     # Check that lang is valid
     check_lang "$lang" "$langurl" "\"$lang\":{\"name\":" || lang_list
-    # Check datadir and make absolute
-    if [[ -d $datadir ]]; then
-	datadir="$(realpath "$datadir")"
-    else
-	error "$datadir: Destination directory does not exist"
+    # Check datadir
+    [[ -d $datadir ]] || error "$datadir: Destination directory does not exist"
+    # Make path absolute
+    datadir="$(realpath "$datadir")"
+    # Add a subdir
+    datadir="$datadir/jwb-$lang"
+    # Create subdir
+    if [[ ! -d $datadir ]]; then
+        mkdir -p "$datadir" || error "$datadir: Failed to create directory"
     fi
-    # Only the parent process has a subdir
-    datadir="$datadir/$bible-$lang"
     # Cleaning
     ((clean)) && clean_dir "$datadir"
 fi
