Improve naming of variables, redo the way the index file is saved, add a write_empty function.

diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -3,10 +3,11 @@
 # functions for jw-scripts
 #
 # Variables that changes the behaviour:
-# filesystem   If true save to dir, else write playlist
+# mode         Valid values: m3u, m3ucompat, filesystem
 # download     If true download the media files
 # child        If true we are subprocess (affects some things)
 # hascurl      If true use curl, else use wget
+# maxrate      Set download rate
 # 
 
 error()
@@ -15,13 +16,12 @@ error()
     exit 1
 }
 
-# Remove everything but the videos
+# Remove everything but the media
 clean_dir()
 {
     local datadir="$1"
-    local datadirname="$(basename "$datadir")"
 
-    [[ $datadir && $datadirname ]] || error "Error in clean_dir()"
+    [[ $datadir ]] || error "Error in $FUNCNAME"
 
     # If dir doesn't exist, it is clean, right?
     [[ ! -d "$datadir" ]] && return 0
@@ -33,36 +33,38 @@ clean_dir()
     # Remove empty directories
     find "$datadir" -type d -exec rmdir --ignore-fail-on-non-empty {} +
     # Remove symlinks outside $datadir that point to $datadir
-    find "$datadir/.." -maxdepth 1 -lname "$datadir/*" -or -lname "$datadirname/*" -delete
+    find "$(dirname "$datadir")" -maxdepth 1 -lname "$datadir/*" -or -lname "$(basename "$datadir")/*" -delete
 }
 
 # Make a link (but smarter)
 # Args: DEST LINKNAME
 create_link()
 {
-    local destdir="$(dirname "$2")"
+    local dest="$1"
+    local link="$2"
+    local linkdir="$(dirname "$link")"
 
-    [[ $1 && $2 && $destdir ]] || error "Error in create_link()"
+    [[ $dest && $link && $linkdir ]] || error "Error in $FUNCNAME"
 
     # Create dir if not there
-    if [[ ! -d $destdir ]]; then
-	mkdir -p "$destdir" || error "$destdir: Failed to create directory"
+    if [[ ! -d $linkdir ]]; then
+	mkdir -p "$linkdir" || error "$linkdir: Failed to create directory"
     fi
         
     # Does link exist?
-    if [[ -L "$2" ]]; then
+    if [[ -L "$link" ]]; then
 	# Is link destination same as we want?
-	if [[ $(readlink "$2") = "$1" ]]; then
+	if [[ $(readlink "$link") = "$dest" ]]; then
 	    return 0
 	else
 	    # If not, remove it
-	    rm "$2" || error "$2: Failed to remove link"
+	    rm "$link" || error "$link: Failed to remove link"
 	fi
     fi
 
     # Make the actual link
-    # -r makes it relative
-    ln -sr "$1" "$2" || error "$2: Failed to create link"
+    # -r makes it relative to link location
+    ln -sr "$dest" "$link" || error "$link: Failed to create link"
 }
 
 # Add newline around squiggly and square brackets and commas
@@ -77,7 +79,7 @@ unsquash_file()
     if [[ $@ ]]; then
         # Append \| to all parameters
         # and remove the last one
-        keywordstring="$(printf '%s\|' "$@" | sed 's/\\|$//')" || error "Error in unsquash_file()"
+        keywordstring="$(printf '%s\|' "$@" | sed 's/\\|$//')" || error "Error in $FUNCNAME"
     else
         # Match everything that's not a citation mark
         keywordstring='[^"]*'
@@ -112,42 +114,18 @@ unsquash_file()
 ' || error "Failed to format JSON"
 }
 
-# Create a link to the CODE outside DATADIR for easy access
-# Args: CODE NAME DATADIR
-create_index_file_link()
-{
-    local code="$1"
-    local name="$2"
-    local datadir="$3"
-
-    [[ $code && $name && $datadir ]] || error "Error in create_index_file_link()"
-    
-    case "$mode" in
-	filesystem)
-            create_link "$datadir/$code" "$datadir/../$name"
-	    ;;
-	m3u)
-            create_link "$datadir/$code.m3u" "$datadir/../$name.m3u"
-	    ;;
-	m3ucompat)
-	    # link to index file not needed in comat mode
-	    # since all files are saved directly in dest dir
-	    return 0 
-	    ;;
-    esac
-}
-
 # Save link to other playlist/dir
 # in current playlist/dir
-# Args: NAME DESTCODE DATADIR CODE
+# Args: NAME DESTCODE DATADIR CODE MAINNAME
 write_subdir()
 {
     local title="$1"
     local link="$2"
     local datadir="$3"
     local code="$4"
-
-    [[ $title && $link && $datadir && $code ]] || error "Error in write_subdir()"
+    local name="$5"
+    
+    [[ $title && $link && $datadir && $code && $name ]] || error "Error in $FUNCNAME"
 
     case "$mode" in
 	filesystem)
@@ -155,10 +133,21 @@ write_subdir()
 	    if [[ ! -d $datadir/$link ]]; then
 		mkdir -p "$datadir/$link" || error "$datadir/$link: Failed to create directory"
 	    fi
-            create_link "$datadir/$link/" "$datadir/$code/$title"
+
+	    # First process saves outside datadir
+            if ! ((child)); then
+		create_link "$datadir/$link" "$(dirname "$datadir")/$name/$title"
+	    else
+		create_link "$datadir/$link" "$datadir/$code/$title"
+	    fi
 	    ;;
 	m3u)
-	    write_to_playlist "$title" "$link.m3u" "$datadir/$code.m3u"
+	    # First process saves playlist outside of datadir
+	    if ! ((child)); then
+		write_to_playlist "$title" "$link.m3u" "$(dirname "$datadir")/$name.m3u"
+	    else
+		write_to_playlist "$title" "$link.m3u" "$datadir/$code.m3u"
+	    fi
 	    ;;
 	m3ucompat)
 	    # no linking to playlists inside playlists in compat mode
@@ -169,7 +158,7 @@ write_subdir()
     return 0
 }
 
-# Save videos in playlist/dir
+# Save media in playlist/dir
 # and optionally download them
 # Args: TITLE LINK DATADIR CODE NAME
 write_media()
@@ -180,8 +169,9 @@ write_media()
     local datadir="$3"
     local code="$4"
     local name="$5"
-
-    [[ $title && $link && $file && $datadir && $code && $name ]] || error "Error in write_media()"
+    local destdir="$datadir"
+    
+    [[ $title && $link && $file && $datadir && $code && $name ]] || error "Error in $FUNCNAME"
 
     # Download media
     if ((download)); then
@@ -191,51 +181,93 @@ write_media()
             download_file "$link" > "$datadir/$file"
         fi
     fi
+
+    # Change link to point to local media (if any)
+    [[ -e $datadir/$file ]] && link="$file"
     
     case "$mode" in
 	filesystem)
+	    # First process saves outside of datadir
+	    if ! ((child)); then
+		destdir="$(dirname "$datadir")"
+		code="$name"
+	    fi
+
+	    # Link to existing media
 	    if [[ -e $datadir/$file ]]; then
-		# Get the file name extension
 		suffix="$(sed -n 's/.\+\.//p' <<< "$file")"
-		# Link to a existing media
-		create_link "$datadir/$file" "$datadir/$code/$title.$suffix"
+		create_link "$datadir/$file" "$destdir/$code/$title.$suffix"
 	    else
 		# Create a playlist with a URL and link to it
 		reset_playlist  "$datadir/$file.m3u"
 		write_to_playlist "$title" "$link" "$datadir/$file.m3u"
-		create_link "$datadir/$file.m3u" "$datadir/$code/$title.m3u"
+		create_link "$datadir/$file.m3u" "$destdir/$code/$title.m3u"
 	    fi
 	    ;;
 	m3u)
-	    # Change link to point to local media (if any)
-	    [[ -e $datadir/$file ]] && link="$file"
-	    # Add the video URL to a playlist
-            write_to_playlist "$title" "$link" "$datadir/$code.m3u"
+	    # First process saves playlist outside of datadir
+	    if ! ((child)); then
+		write_to_playlist "$title" "$link" "$(dirname "$datadir")/$name.m3u"
+	    else
+		write_to_playlist "$title" "$link" "$datadir/$code.m3u"
+	    fi
 	    ;;
 	m3ucompat)
-	    # Change link to point to local media (if any)
-	    if [[ -e $datadir/$file ]]; then
-		local datadirname="$(basename "$datadir")"
-		[[ $datadirname ]] || error "Error in write_media()"
-		link="$datadirname/$file"
-	    fi
-	    # Step out of the "datadir" subdir we steped into earlier
-	    ((child)) && datadir="$datadir/.."
-	    # Add the video URL to a playlist
-	    write_to_playlist "$title" "$link" "$datadir/$code $name.m3u"
+	    # Save all playlists outside of datadir
+	    datadir="$(dirname "$datadir")"
+
+	    write_to_playlist "$title" "$link" "$datadir/$code - $name.m3u"
 	    ;;
     esac
     
     return 0
 }
 
+# Args: DATADIR CODE NAME
+write_empty()
+{
+    local dir="$1"
+    local code="$2"
+    local name="$3"
+    local file
+
+    [[ $dir && $code && $name ]] || error "Error in $FUNCNAME"
+
+    case "$mode" in
+	m3u)
+	    # First process saves outside of datadir
+	    if ! ((child)); then
+		dir="$(dirname "$dir")"
+		file="$name.m3u"
+	    else
+		file="$code.m3u"
+	    fi
+	    ;;
+	m3ucompat)
+	    dir="$(dirname "$dir")"
+	    file="$code - $name.m3u"
+	    ;;
+	filesystem)
+	    # Remove m3u files that is linked to
+	    # Don't do this because they may be used in someother dir
+	    #find -L -lname "*.m3u" -delete
+
+	    # Remove all links
+	    [[ -e $dir/$code ]] && find "$dir/$code" -type l -delete
+	    return
+	    ;;
+    esac
+
+    reset_playlist "$dir/$file"
+}
+
 # Args: FILE
 reset_playlist()
 {
     local file="$1"
-    local dir=$(dirname "$1")
+    local dir="$(dirname "$1")"
 
-    [[ $file && $dir ]] || error "Error in reset_playlist()"
+    [[ $file && $dir ]] || error "Error in $FUNCNAME"
     
     [[ -d $dir ]] || mkdir -p "$dir" || error "$dir:  Failed to create directory"
     printf '%s\n' "#EXTM3U" > "$file" || error "$file: Failed to write to playlist"
@@ -248,22 +280,18 @@ write_to_playlist()
     local link="$2"
     local file="$3"
 
-    [[ $title && $link && $file ]] || error "Error in write_to_playlist()"
+    [[ $title && $link && $file ]] || error "Error in $FUNCNAME"
         
     # Reset the file if empty
-    if [[ ! -f $file ]]; then
-	reset_playlist "$file"
-    fi
+    [[ ! -f $file ]] && reset_playlist "$file"
 
-    # If we are the first process, and the link is local a file
-    # add the subdir to the link (since first process saves
-    # outside the subdir)
-    if ! ((child)) && [[ ! $link =~ ^https?:// ]]; then
-	local subdir="$(basename "$(realpath -m "$datadir")")"
-	[[ $subdir ]] || error "Error in write_to_playlist()"
-	link="$subdir/$link"
+    # Make links to local files relative to the playlist dir
+    if [[ ! $link =~ ^https?:// ]]; then
+	# --canonicalize-missing = don't care if file exists or not
+	link="$(realpath --canonicalize-missing --relative-to="$(dirname "$file")" "$datadir/$link")"
+	[[ $link ]] || error "Error in $FUNCNAME"
     fi
-
+    
     # If link already is written to file, skip it
     grep -q "^$link$" "$file" && return 0
     
@@ -314,7 +342,7 @@ read_arguments()
     until [[ $1 = -- ]]; do
         flags+=("$1")
         shift
-        [[ $# = 0 ]] && error "Error in read_arguments()"
+        [[ $# = 0 ]] && error "Error in $FUNCNAME"
     done
 
     # Remove the --
@@ -369,7 +397,7 @@ read_arguments()
 # Args: LANGCODE URL PATTERN
 check_lang()
 {
-    [[ $1 && $2 && $3 ]] || error "Error in check_lang()"
+    [[ $1 && $2 && $3 ]] || error "Error in $FUNCNAME"
 
     [[ $1 = E || $NOCHECKLANG = 1 ]] && return 0
     # Don't make more checks
